# Generated by Django 5.1.15 on 2026-08-31 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_location_created_at_location_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "trait_type",
                    models.CharField(
                        choices=[
                            ("categorical_nominal", "Categorical (Nominal)"),
                            ("categorical_ordinal", "Categorical (Ordinal)"),
                            ("numerical_continuous", "Numerical (Continuous)"),
                            ("numerical_discrete", "Numerical (Discrete)"),
                            ("text", "Text"),
                        ],
                        max_length=50,
                    ),
                ),
                ("scale_min", models.FloatField(blank=True, null=True)),
                ("scale_max", models.FloatField(blank=True, null=True)),
                ("units", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_traits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
