# Generated by Django 5.1.15 on 2026-08-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_trait"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="trait_type",
            field=models.CharField(
                choices=[
                    ("categorical_nominal", "Categorical (Nominal)"),
                    ("categorical_ordinal", "Categorical (Ordinal)"),
                    ("numerical_continuous", "Numerical (Continuous)"),
                    ("numerical_discrete", "Numerical (Discrete)"),
                    ("text", "Text"),
                    ("date", "Date"),
                    ("datetime", "Date & Time"),
                ],
                max_length=50,
            ),
        ),
    ]
