# Generated by Django 5.1.15 on 2026-09-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_trait_trait_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trait',
        ),
    ]
