# Generated by Django 5.1.15 on 2026-09-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='crop',
            field=models.CharField(choices=[('wheat', 'Bread Wheat (Triticum aestivum)'), ('durum_wheat', 'Durum Wheat (Triticum durum)'), ('barley', 'Barley (Hordeum vulgare)'), ('triticale', 'Triticale (x Triticosecale)'), ('oats', 'Oats (Avena sativa)'), ('rye', 'Rye (Secale cereale)'), ('other', 'Other Crop')], default='wheat', max_length=255),
        ),
    ]
