# Generated by hand for the initial scaffold.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('germplasm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('trial_code', models.CharField(max_length=255, unique=True)),
                ('brapi_study_db_id', models.CharField(blank=True, max_length=255)),
                ('design_type', models.CharField(choices=[('RCBD', 'RCBD'), ('alpha_lattice', 'Alpha-lattice'), ('augmented', 'Augmented'), ('unreplicated', 'Unreplicated'), ('other', 'Other')], default='RCBD', max_length=32)),
                ('num_reps', models.IntegerField(default=1)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.program')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
            ],
            options={
                'ordering': ['trial_code'],
            },
        ),
        migrations.CreateModel(
            name='ObservationVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('variable_code', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=64)),
                ('data_type', models.CharField(choices=[('numeric', 'Numeric'), ('integer', 'Integer'), ('categorical', 'Categorical'), ('text', 'Text'), ('date', 'Date')], default='numeric', max_length=16)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'observation variables',
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.IntegerField()),
                ('block', models.IntegerField(blank=True, null=True)),
                ('plot_number', models.IntegerField()),
                ('row', models.IntegerField(blank=True, null=True)),
                ('column', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('planted', 'Planted'), ('harvested', 'Harvested'), ('discarded', 'Discarded')], default='planned', max_length=32)),
                ('germplasm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='germplasm.germplasm')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='trials.trial')),
            ],
            options={
                'unique_together': {('trial', 'plot_number')},
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_time', models.DateTimeField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True)),
                ('value_numeric', models.FloatField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='trials.plot')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='trials.observationvariable')),
            ],
            options={
                'ordering': ['plot', 'variable'],
            },
        ),
    ]
