# Generated by hand for database optimization updates.

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='trial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observationvariable',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
