# Generated by Django 5.1.15 on 2026-08-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0006_analysisset'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='prep_fraction',
            field=models.FloatField(blank=True, help_text='Fraction of test entries to partially replicate (P-Rep designs, 0.0–1.0). Default 0.25.', null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='block_size',
            field=models.PositiveIntegerField(blank=True, help_text='Incomplete block size for alpha-lattice and augmented block designs.', null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='design_type',
            field=models.CharField(choices=[('RCBD', 'RCBD'), ('alpha_lattice', 'Alpha-lattice'), ('augmented', 'Augmented'), ('prep', 'P-Rep'), ('latin_square', 'Latin Square'), ('augmented_block', 'Augmented Block'), ('unreplicated', 'Unreplicated'), ('other', 'Other')], default='RCBD', max_length=32),
        ),
    ]
