# Generated by Django 5.1.15 on 2026-09-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0007_trial_prep_fraction_alter_trial_block_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationvariable',
            name='crop',
            field=models.CharField(blank=True, default='all', help_text="Standard crop scope (e.g. wheat, barley, or 'all')", max_length=64),
        ),
    ]
