# Generated by Django 5.1.15 on 2026-09-05 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_program_updated_at_alter_program_crop'),
        ('trials', '0008_observationvariable_crop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='observationvariable',
            name='categorical_options',
            field=models.JSONField(blank=True, default=list, help_text="Valid option strings for categorical traits, e.g. ['1','2','3','4','5']"),
        ),
        migrations.AddField(
            model_name='observationvariable',
            name='category',
            field=models.CharField(blank=True, choices=[('morphological', 'Morphological'), ('agronomic', 'Agronomic'), ('disease', 'Disease Resistance'), ('quality', 'Grain Quality'), ('phenology', 'Phenology'), ('abiotic', 'Abiotic Stress'), ('other', 'Other')], db_index=True, default='other', help_text='Trait category for library organisation.', max_length=20),
        ),
        migrations.AddField(
            model_name='trial',
            name='generation',
            field=models.IntegerField(blank=True, help_text='Breeding generation index (0=F0, 1=F1, etc.) for pipeline tracking.', null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='active', max_length=16),
        ),
        migrations.CreateModel(
            name='TraitPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('morphological', 'Morphological'), ('agronomic', 'Agronomic'), ('disease', 'Disease Resistance'), ('quality', 'Grain Quality'), ('phenology', 'Phenology'), ('abiotic', 'Abiotic Stress'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, help_text='If null, panel is available to all programs.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trait_panels', to='core.program')),
                ('variables', models.ManyToManyField(blank=True, related_name='panels', to='trials.observationvariable')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
