# Generated by Django 5.1.15 on 2026-09-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0009_versatility_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='is_border',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trial',
            name='advancement_direction',
            field=models.CharField(choices=[('up', 'Up'), ('right', 'Right'), ('up_right', 'Up then Right'), ('right_up', 'Right then Up')], default='up', max_length=16),
        ),
        migrations.AddField(
            model_name='trial',
            name='field_cols',
            field=models.PositiveIntegerField(blank=True, help_text='Total physical field grid columns.', null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='field_rows',
            field=models.PositiveIntegerField(blank=True, help_text='Total physical field grid rows.', null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='layout_schema',
            field=models.CharField(choices=[('h_serpentine', 'Horizontal Serpentine'), ('v_serpentine', 'Vertical Serpentine'), ('h_cartesian', 'Horizontal Cartesian'), ('v_cartesian', 'Vertical Cartesian')], default='h_serpentine', max_length=20),
        ),
        migrations.AddField(
            model_name='trial',
            name='starting_corner',
            field=models.CharField(choices=[('BL', 'Bottom-Left'), ('BR', 'Bottom-Right'), ('TL', 'Top-Left'), ('TR', 'Top-Right')], default='BL', max_length=4),
        ),
    ]
