# Generated by Django 5.1.15 on 2026-09-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0010_plot_is_border_trial_advancement_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='purpose',
            field=models.CharField(choices=[('yield_trial', 'Yield Trial'), ('screening_nursery', 'Screening Nursery'), ('advancement_nursery', 'Advancement Nursery'), ('other', 'Other')], db_index=True, default='yield_trial', max_length=32),
        ),
    ]
