# Generated by Django 5.1.15 on 2026-09-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0012_observationvariable_scoring_guide_observationphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationvariable',
            name='categorical_states',
            field=models.JSONField(blank=True, default=dict, help_text='For categorical variables: state code to label, e.g. {"1": "White", "2": "Red"}.'),
        ),
        migrations.AddField(
            model_name='observationvariable',
            name='is_dus_descriptor',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this is a standard UPOV-style DUS characterization trait, for filtering/export toward regulatory submission.'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='purpose',
            field=models.CharField(choices=[('yield_trial', 'Yield Trial'), ('screening_nursery', 'Screening Nursery'), ('advancement_nursery', 'Advancement Nursery'), ('phytotron_cycle', 'Phytotron / Rapid-Cycling'), ('other', 'Other')], db_index=True, default='yield_trial', max_length=32),
        ),
    ]
