# Generated by hand for the initial scaffold.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Germplasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('germplasm_db_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('species', models.CharField(default='Triticum aestivum', max_length=100)),
                ('pedigree_string', models.CharField(blank=True, help_text='Free-text pedigree notation, e.g. "KAUZ/PASTOR".', max_length=500)),
                ('cross_type', models.CharField(choices=[('biparental', 'Biparental cross'), ('self', 'Self-pollinated'), ('backcross', 'Backcross'), ('doubled_haploid', 'Doubled haploid'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('year_developed', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_female', models.ForeignKey(blank=True, help_text='Female (seed) parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='female_progeny', to='germplasm.germplasm')),
                ('parent_male', models.ForeignKey(blank=True, help_text='Male (pollen) parent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='male_progeny', to='germplasm.germplasm')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='germplasm', to='core.program')),
            ],
            options={
                'verbose_name_plural': 'germplasm',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cross_code', models.CharField(max_length=100, unique=True)),
                ('cross_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('female_parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crosses_as_female', to='germplasm.germplasm')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
                ('male_parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crosses_as_male', to='germplasm.germplasm')),
            ],
            options={
                'verbose_name_plural': 'crosses',
                'ordering': ['-cross_date'],
            },
        ),
    ]
