# Generated by hand for database optimization updates.

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("germplasm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="germplasm",
            name="name",
            field=models.CharField(db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="cross",
            name="cross_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AddField(
            model_name="germplasm",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cross",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cross",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
