# Generated by Django 5.1.15 on 2026-08-23 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location_created_at_location_created_by_and_more'),
        ('germplasm', '0003_germplasm_created_by_germplasm_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cross',
            name='is_reciprocal',
            field=models.BooleanField(default=False, help_text='Whether this is a reciprocal of another cross'),
        ),
        migrations.AddField(
            model_name='cross',
            name='map_position',
            field=models.PositiveIntegerField(blank=True, help_text='Position in the crossing block sowing map', null=True),
        ),
        migrations.AddField(
            model_name='cross',
            name='progeny',
            field=models.ForeignKey(blank=True, help_text='Auto-created progeny germplasm entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_cross', to='germplasm.germplasm'),
        ),
        migrations.AddField(
            model_name='cross',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('pollinated', 'Pollinated'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='CrossingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('map_pattern', models.CharField(choices=[('male_first', 'Common male then females'), ('female_first', 'Common female then males'), ('alternating', 'Alternating male/female')], default='male_first', max_length=30)),
                ('include_reciprocals', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossing_blocks', to='core.program')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crossing_blocks', to='core.season')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cross',
            name='crossing_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crosses', to='germplasm.crossingblock'),
        ),
    ]
