# Generated by Django 5.1.15 on 2026-08-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0004_crossing_block_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='germplasm',
            name='generation',
            field=models.IntegerField(default=0, help_text='Generation index (0=F0, 1=F1, ..., 8=F8+)'),
        ),
    ]
