# Generated by Django 5.1.15 on 2026-08-31 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("germplasm", "0005_germplasm_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="germplasm",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
