# Generated by Django 5.1.15 on 2026-09-04 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_trait'),
        ('germplasm', '0006_germplasm_is_archived'),
        ('trials', '0007_trial_prep_fraction_alter_trial_block_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_code', models.CharField(db_index=True, help_text='Unique seed packet identifier, e.g. LOT-2026-0042', max_length=100, unique=True)),
                ('quantity_grams', models.FloatField(default=0.0)),
                ('seed_count', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_location', models.CharField(help_text='Physical location: e.g. Cold Room 1, Rack C, Box 12', max_length=200)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('germination_rate', models.FloatField(blank=True, help_text='Germination rate percentage (0.0 to 100.0)', null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('depleted', 'Depleted'), ('reserved', 'Reserved'), ('quarantine', 'Quarantine')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('germplasm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seed_lots', to='germplasm.germplasm')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_lots', to='core.program')),
                ('source_plot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvested_seed_lots', to='trials.plot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seed Lot',
                'verbose_name_plural': 'Seed Lots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('initial_deposit', 'Initial Deposit'), ('harvest_deposit', 'Harvest Deposit'), ('planting_deduction', 'Planting Deduction'), ('distribution', 'Distribution'), ('adjustment', 'Inventory Adjustment')], max_length=30)),
                ('quantity_grams', models.FloatField(help_text='Delta in grams (positive for deposit, negative for deduction)')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination_trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_transactions', to='trials.trial')),
                ('seed_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='germplasm.seedlot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
