# Generated by Django 5.1.15 on 2026-09-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0007_seedlot_seedtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='germplasm',
            name='is_check',
            field=models.BooleanField(db_index=True, default=False, help_text='True for permanent check/reference lines used across trials.'),
        ),
        migrations.AddField(
            model_name='germplasm',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Free-form tags, e.g. ['drought-tolerant', 'release-candidate']"),
        ),
    ]
