# Generated by Django 5.1.15 on 2026-09-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0008_versatility_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedlot',
            name='germination_date',
            field=models.DateField(blank=True, help_text='Date of last germination test', null=True),
        ),
        migrations.AddField(
            model_name='seedlot',
            name='reserved_grams',
            field=models.FloatField(default=0.0, help_text='Quantity reserved for pending trials or distributions'),
        ),
        migrations.AlterField(
            model_name='seedlot',
            name='storage_location',
            field=models.CharField(blank=True, default='', help_text='Physical location: e.g. Cold Room 1, Rack C, Box 12', max_length=200),
        ),
    ]
