# Generated by Django 5.1.15 on 2026-09-19 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userpreference'),
        ('germplasm', '0009_seedlot_germination_date_seedlot_reserved_grams_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionShortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('mea', 'Multi-Environment Ranking'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('germplasm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_entries', to='germplasm.germplasm')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlist_entries', to='core.program')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shortlist_entries', to='core.season')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('germplasm', 'program')},
            },
        ),
    ]
