# Generated by Django 5.1.15 on 2026-09-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('germplasm', '0010_selectionshortlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='germplasm',
            name='release_status',
            field=models.CharField(choices=[('breeding_line', 'Breeding Line'), ('release_candidate', 'Release Candidate'), ('released', 'Released Variety'), ('discontinued', 'Discontinued')], db_index=True, default='breeding_line', max_length=20),
        ),
    ]
