# Generated by Django 5.1.15 on 2026-09-19 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sharelink_weatherobservation'),
        ('germplasm', '0011_germplasm_release_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cross',
            name='seed_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of F1 seeds harvested from this cross.', null=True),
        ),
        migrations.AddField(
            model_name='germplasm',
            name='external_accession_id',
            field=models.CharField(blank=True, db_index=True, help_text='Original ID from the source institution (CIMMYT, national genebank, another program, etc.), preserved even after internal renumbering.', max_length=200),
        ),
        migrations.CreateModel(
            name='VarietyMaintenanceCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('ear_to_row', 'Ear-to-Row / Head-Row Selection'), ('nucleus_seed', 'Nucleus Seed System'), ('mass_selection', 'Mass Selection'), ('other', 'Other')], max_length=32)),
                ('cycle_number', models.PositiveIntegerField(help_text="Sequential cycle number for this variety's maintenance history.")),
                ('off_types_removed', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_cycles', to='core.season')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_cycles', to='germplasm.germplasm')),
            ],
            options={
                'ordering': ['variety', 'cycle_number'],
                'unique_together': {('variety', 'cycle_number')},
            },
        ),
    ]
