# Generated by Django 5.1.15 on 2026-09-11 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_program_updated_at_alter_program_crop'),
        ('germplasm', '0009_seedlot_germination_date_seedlot_reserved_grams_and_more'),
        ('trials', '0010_plot_is_border_trial_advancement_direction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('gene_symbol', models.CharField(blank=True, max_length=100)),
                ('chromosome', models.CharField(blank=True, help_text='Wheat chromosome (e.g. 7D, 3B, 4A, 2D)', max_length=20)),
                ('target_trait', models.CharField(help_text='Target trait (e.g. Leaf Rust Resistance, Semi-dwarf)', max_length=150)),
                ('trait_category', models.CharField(choices=[('disease', 'Disease Resistance'), ('agronomic', 'Agronomic / Yield'), ('quality', 'Grain Quality'), ('phenology', 'Phenology / Adaptation'), ('abiotic', 'Abiotic Stress')], db_index=True, default='disease', max_length=50)),
                ('favorable_allele', models.CharField(help_text='Allele indicating favorable/resistant state', max_length=50)),
                ('unfavorable_allele', models.CharField(blank=True, help_text='Allele indicating susceptible/wildtype state', max_length=50)),
                ('assay_type', models.CharField(choices=[('KASP', 'KASP Assay'), ('TaqMan', 'TaqMan Probe'), ('PCR_Gel', 'Gel / STS / CAPS PCR'), ('SNP_Chip', 'SNP Array Probe')], default='KASP', max_length=50)),
                ('effect_description', models.TextField(blank=True, help_text='Phenotypic effect explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, help_text='If null, marker is globally available across programs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_markers', to='core.program')),
            ],
            options={
                'ordering': ['trait_category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GenotypeDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('species', models.CharField(default='Triticum aestivum', max_length=100)),
                ('file_format', models.CharField(choices=[('matrix', 'Dosage Matrix (.csv/.tsv)'), ('vcf', 'Variant Call Format (.vcf)'), ('hapmap', 'HapMap (.hmp.txt)')], default='matrix', max_length=32)),
                ('marker_count', models.PositiveIntegerField(default=0)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('marker_names', models.JSONField(blank=True, default=list, help_text='Ordered list of marker identifier strings')),
                ('sample_names', models.JSONField(blank=True, default=list, help_text='Ordered list of sample/germplasm identifier strings')),
                ('imputation_method', models.CharField(choices=[('mean', 'Mean Allele Dosage'), ('mode', 'Mode Genotype'), ('none', 'None (No Imputation)')], default='mean', max_length=32)),
                ('maf_threshold', models.FloatField(default=0.05, help_text='Minor Allele Frequency filter threshold applied during import')),
                ('matrix_data', models.JSONField(blank=True, default=dict, help_text='Encoded dosage dictionary: sample_id -> list of numeric dosages (0.0 to 2.0)')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genotype_datasets', to='core.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenomicPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('model_type', models.CharField(choices=[('gblup', 'GBLUP (VanRaden GRM)'), ('rrblup', 'Ridge Regression BLUP (rrBLUP)')], default='gblup', max_length=32)),
                ('n_training', models.PositiveIntegerField(default=0, help_text='Number of observed training lines')),
                ('n_candidates', models.PositiveIntegerField(default=0, help_text='Number of candidate lines predicted without field trial')),
                ('cv_accuracy', models.FloatField(blank=True, help_text='5-fold cross validation Pearson correlation r(GEBV, y)', null=True)),
                ('cv_mse', models.FloatField(blank=True, help_text='Mean squared error in cross-validation', null=True)),
                ('genomic_heritability', models.FloatField(blank=True, help_text='SNP broad-sense heritability h²_SNP', null=True)),
                ('variance_genomic', models.FloatField(blank=True, null=True)),
                ('variance_residual', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomic_predictions', to='core.program')),
                ('training_analysis_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genomic_predictions', to='trials.analysisset')),
                ('training_trial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genomic_predictions', to='trials.trial')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomic_predictions', to='trials.observationvariable')),
                ('genotype_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='genomics.genotypedataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenomicBreedingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200)),
                ('gebv', models.FloatField(help_text='Genomic Estimated Breeding Value')),
                ('reliability', models.FloatField(default=0.0, help_text='Reliability index r² (0.0 to 1.0)')),
                ('standard_error', models.FloatField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('is_training', models.BooleanField(default=False, help_text='True if line had observed phenotype in the training trial')),
                ('observed_phenotype', models.FloatField(blank=True, help_text='Phenotypic BLUE/mean if in training set', null=True)),
                ('germplasm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gebv_records', to='germplasm.germplasm')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gebvs', to='genomics.genomicprediction')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('prediction', 'germplasm')},
            },
        ),
        migrations.CreateModel(
            name='GenotypeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(db_index=True, max_length=200)),
                ('call_rate', models.FloatField(default=1.0)),
                ('heterozygosity', models.FloatField(default=0.0)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='genomics.genotypedataset')),
                ('germplasm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genotype_samples', to='germplasm.germplasm')),
            ],
            options={
                'ordering': ['sample_id'],
                'unique_together': {('dataset', 'sample_id')},
            },
        ),
        migrations.CreateModel(
            name='MarkerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_status', models.CharField(choices=[('favorable', 'Favorable (Resistant / Desired)'), ('heterozygous', 'Heterozygous (Carrier)'), ('unfavorable', 'Unfavorable (Susceptible / Wildtype)'), ('missing', 'Missing / No Call')], db_index=True, default='missing', max_length=30)),
                ('raw_genotype', models.CharField(blank=True, help_text='Raw allele string e.g. A:A, T:T, FAM, HEX', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('germplasm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker_scores', to='germplasm.germplasm')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='genomics.diagnosticmarker')),
            ],
            options={
                'ordering': ['marker', 'germplasm'],
                'unique_together': {('marker', 'germplasm')},
            },
        ),
    ]
