# Generated by Django 5.1.15 on 2026-09-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genomics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genomicprediction',
            name='mu',
            field=models.FloatField(blank=True, help_text='Population mean (fixed-effect intercept) from the GBLUP solve', null=True),
        ),
    ]
